development:
  #adapter: async
  adapter: redis
  url: <%= "redis://#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}" %>

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
